name: scp pipeline
on:
  push:
    branches:
      - master

env:
  TARGET_DIR: /home/github/test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: scp pipeline
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          local: './test/*'
          remote: /home/github/test/
          scp: |
            './test/test*.csv' => "$TARGET_DIR/test2/"
            '.' => $TARGET_DIR

      - name: local remote scp 1
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          port: ${{ secrets.DC_PORT }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          local: "./test/test1*"
          remote: /home/github/test/test1/

      - name: local remote scp 2
        uses: cross-the-world/scp-pipeline@master
        env:
          TO_DIR: /home/github/test/test3/
        with:
          host: ${{ secrets.DC_HOST }}
          port: ${{ secrets.DC_PORT }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          local: "."
          remote: $TO_DIR

      - name: local remote scp 3
        uses: cross-the-world/scp-pipeline@master
        env:
          TO_DIR: /home/github/test/test3/
        with:
          host: ${{ secrets.DC_HOST }}
          port: ${{ secrets.DC_PORT }}
          user: ${{ secrets.DC_USER }}
          key: ${{ secrets.DC_KEY }}
          local: "."
          remote: $TO_DIR